/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.employee.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EmployeeDetail service. Represents a row in the &quot;IgnekIntranet_EmployeeDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.employee.service.model.impl.EmployeeDetailModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.employee.service.model.impl.EmployeeDetailImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetail
 * @generated
 */
@ProviderType
public interface EmployeeDetailModel
	extends BaseModel<EmployeeDetail>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a employee detail model instance should use the {@link EmployeeDetail} interface instead.
	 */

	/**
	 * Returns the primary key of this employee detail.
	 *
	 * @return the primary key of this employee detail
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this employee detail.
	 *
	 * @param primaryKey the primary key of this employee detail
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this employee detail.
	 *
	 * @return the uuid of this employee detail
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this employee detail.
	 *
	 * @param uuid the uuid of this employee detail
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the employee ID of this employee detail.
	 *
	 * @return the employee ID of this employee detail
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this employee detail.
	 *
	 * @param employeeId the employee ID of this employee detail
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the group ID of this employee detail.
	 *
	 * @return the group ID of this employee detail
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this employee detail.
	 *
	 * @param groupId the group ID of this employee detail
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this employee detail.
	 *
	 * @return the company ID of this employee detail
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this employee detail.
	 *
	 * @param companyId the company ID of this employee detail
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this employee detail.
	 *
	 * @return the user ID of this employee detail
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this employee detail.
	 *
	 * @param userId the user ID of this employee detail
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this employee detail.
	 *
	 * @return the user uuid of this employee detail
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this employee detail.
	 *
	 * @param userUuid the user uuid of this employee detail
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this employee detail.
	 *
	 * @return the user name of this employee detail
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this employee detail.
	 *
	 * @param userName the user name of this employee detail
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this employee detail.
	 *
	 * @return the create date of this employee detail
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this employee detail.
	 *
	 * @param createDate the create date of this employee detail
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this employee detail.
	 *
	 * @return the modified date of this employee detail
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this employee detail.
	 *
	 * @param modifiedDate the modified date of this employee detail
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the first name of this employee detail.
	 *
	 * @return the first name of this employee detail
	 */
	@AutoEscape
	public String getFirstName();

	/**
	 * Sets the first name of this employee detail.
	 *
	 * @param firstName the first name of this employee detail
	 */
	public void setFirstName(String firstName);

	/**
	 * Returns the last name of this employee detail.
	 *
	 * @return the last name of this employee detail
	 */
	@AutoEscape
	public String getLastName();

	/**
	 * Sets the last name of this employee detail.
	 *
	 * @param lastName the last name of this employee detail
	 */
	public void setLastName(String lastName);

	/**
	 * Returns the email of this employee detail.
	 *
	 * @return the email of this employee detail
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this employee detail.
	 *
	 * @param email the email of this employee detail
	 */
	public void setEmail(String email);

	/**
	 * Returns the phone number of this employee detail.
	 *
	 * @return the phone number of this employee detail
	 */
	public long getPhoneNumber();

	/**
	 * Sets the phone number of this employee detail.
	 *
	 * @param phoneNumber the phone number of this employee detail
	 */
	public void setPhoneNumber(long phoneNumber);

	/**
	 * Returns the address line1 of this employee detail.
	 *
	 * @return the address line1 of this employee detail
	 */
	@AutoEscape
	public String getAddressLine1();

	/**
	 * Sets the address line1 of this employee detail.
	 *
	 * @param addressLine1 the address line1 of this employee detail
	 */
	public void setAddressLine1(String addressLine1);

	/**
	 * Returns the address line2 of this employee detail.
	 *
	 * @return the address line2 of this employee detail
	 */
	@AutoEscape
	public String getAddressLine2();

	/**
	 * Sets the address line2 of this employee detail.
	 *
	 * @param addressLine2 the address line2 of this employee detail
	 */
	public void setAddressLine2(String addressLine2);

	/**
	 * Returns the city of this employee detail.
	 *
	 * @return the city of this employee detail
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this employee detail.
	 *
	 * @param city the city of this employee detail
	 */
	public void setCity(String city);

	/**
	 * Returns the zip code of this employee detail.
	 *
	 * @return the zip code of this employee detail
	 */
	public long getZipCode();

	/**
	 * Sets the zip code of this employee detail.
	 *
	 * @param zipCode the zip code of this employee detail
	 */
	public void setZipCode(long zipCode);

	/**
	 * Returns the designation of this employee detail.
	 *
	 * @return the designation of this employee detail
	 */
	@AutoEscape
	public String getDesignation();

	/**
	 * Sets the designation of this employee detail.
	 *
	 * @param designation the designation of this employee detail
	 */
	public void setDesignation(String designation);

	@Override
	public EmployeeDetail cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}