/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.employee.service.model.impl;

import java.io.Serializable;
import java.lang.reflect.InvocationHandler;
import java.sql.Blob;
import java.sql.Types;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import com.employee.service.model.EmployeeDetail;
import com.employee.service.model.EmployeeDetailModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

/**
 * The base model implementation for the EmployeeDetail service. Represents a row in the &quot;IgnekIntranet_EmployeeDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>EmployeeDetailModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetailImpl
 * @generated
 */
public class EmployeeDetailModelImpl
	extends BaseModelImpl<EmployeeDetail> implements EmployeeDetailModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee detail model instance should use the <code>EmployeeDetail</code> interface instead.
	 */
	public static final String TABLE_NAME = "IgnekIntranet_EmployeeDetail";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"employeeId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"firstName", Types.VARCHAR}, {"lastName", Types.VARCHAR},
		{"email", Types.VARCHAR}, {"phoneNumber", Types.BIGINT},
		{"addressLine1", Types.VARCHAR}, {"addressLine2", Types.VARCHAR},
		{"city", Types.VARCHAR}, {"zipCode", Types.BIGINT},
		{"designation", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("employeeId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("firstName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("lastName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("phoneNumber", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("addressLine1", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("addressLine2", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("city", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("zipCode", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("designation", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table IgnekIntranet_EmployeeDetail (uuid_ VARCHAR(75) null,employeeId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,email VARCHAR(75) null,phoneNumber LONG,addressLine1 VARCHAR(75) null,addressLine2 VARCHAR(75) null,city VARCHAR(75) null,zipCode LONG,designation VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table IgnekIntranet_EmployeeDetail";

	public static final String ORDER_BY_JPQL =
		" ORDER BY employeeDetail.employeeId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY IgnekIntranet_EmployeeDetail.employeeId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EMPLOYEEID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public EmployeeDetailModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setEmployeeId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _employeeId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return EmployeeDetail.class;
	}

	@Override
	public String getModelClassName() {
		return EmployeeDetail.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<EmployeeDetail, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<EmployeeDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDetail, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((EmployeeDetail)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<EmployeeDetail, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<EmployeeDetail, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(EmployeeDetail)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<EmployeeDetail, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<EmployeeDetail, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<EmployeeDetail, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<EmployeeDetail, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<EmployeeDetail, Object>>();

			attributeGetterFunctions.put("uuid", EmployeeDetail::getUuid);
			attributeGetterFunctions.put(
				"employeeId", EmployeeDetail::getEmployeeId);
			attributeGetterFunctions.put("groupId", EmployeeDetail::getGroupId);
			attributeGetterFunctions.put(
				"companyId", EmployeeDetail::getCompanyId);
			attributeGetterFunctions.put("userId", EmployeeDetail::getUserId);
			attributeGetterFunctions.put(
				"userName", EmployeeDetail::getUserName);
			attributeGetterFunctions.put(
				"createDate", EmployeeDetail::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", EmployeeDetail::getModifiedDate);
			attributeGetterFunctions.put(
				"firstName", EmployeeDetail::getFirstName);
			attributeGetterFunctions.put(
				"lastName", EmployeeDetail::getLastName);
			attributeGetterFunctions.put("email", EmployeeDetail::getEmail);
			attributeGetterFunctions.put(
				"phoneNumber", EmployeeDetail::getPhoneNumber);
			attributeGetterFunctions.put(
				"addressLine1", EmployeeDetail::getAddressLine1);
			attributeGetterFunctions.put(
				"addressLine2", EmployeeDetail::getAddressLine2);
			attributeGetterFunctions.put("city", EmployeeDetail::getCity);
			attributeGetterFunctions.put("zipCode", EmployeeDetail::getZipCode);
			attributeGetterFunctions.put(
				"designation", EmployeeDetail::getDesignation);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<EmployeeDetail, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<EmployeeDetail, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<EmployeeDetail, ?>>();

			attributeSetterBiConsumers.put(
				"uuid",
				(BiConsumer<EmployeeDetail, String>)EmployeeDetail::setUuid);
			attributeSetterBiConsumers.put(
				"employeeId",
				(BiConsumer<EmployeeDetail, Long>)
					EmployeeDetail::setEmployeeId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<EmployeeDetail, Long>)EmployeeDetail::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<EmployeeDetail, Long>)EmployeeDetail::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<EmployeeDetail, Long>)EmployeeDetail::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<EmployeeDetail, String>)
					EmployeeDetail::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<EmployeeDetail, Date>)
					EmployeeDetail::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<EmployeeDetail, Date>)
					EmployeeDetail::setModifiedDate);
			attributeSetterBiConsumers.put(
				"firstName",
				(BiConsumer<EmployeeDetail, String>)
					EmployeeDetail::setFirstName);
			attributeSetterBiConsumers.put(
				"lastName",
				(BiConsumer<EmployeeDetail, String>)
					EmployeeDetail::setLastName);
			attributeSetterBiConsumers.put(
				"email",
				(BiConsumer<EmployeeDetail, String>)EmployeeDetail::setEmail);
			attributeSetterBiConsumers.put(
				"phoneNumber",
				(BiConsumer<EmployeeDetail, Long>)
					EmployeeDetail::setPhoneNumber);
			attributeSetterBiConsumers.put(
				"addressLine1",
				(BiConsumer<EmployeeDetail, String>)
					EmployeeDetail::setAddressLine1);
			attributeSetterBiConsumers.put(
				"addressLine2",
				(BiConsumer<EmployeeDetail, String>)
					EmployeeDetail::setAddressLine2);
			attributeSetterBiConsumers.put(
				"city",
				(BiConsumer<EmployeeDetail, String>)EmployeeDetail::setCity);
			attributeSetterBiConsumers.put(
				"zipCode",
				(BiConsumer<EmployeeDetail, Long>)EmployeeDetail::setZipCode);
			attributeSetterBiConsumers.put(
				"designation",
				(BiConsumer<EmployeeDetail, String>)
					EmployeeDetail::setDesignation);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getEmployeeId() {
		return _employeeId;
	}

	@Override
	public void setEmployeeId(long employeeId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_employeeId = employeeId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return "";
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_firstName = firstName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return "";
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_lastName = lastName;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@Override
	public long getPhoneNumber() {
		return _phoneNumber;
	}

	@Override
	public void setPhoneNumber(long phoneNumber) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_phoneNumber = phoneNumber;
	}

	@Override
	public String getAddressLine1() {
		if (_addressLine1 == null) {
			return "";
		}
		else {
			return _addressLine1;
		}
	}

	@Override
	public void setAddressLine1(String addressLine1) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addressLine1 = addressLine1;
	}

	@Override
	public String getAddressLine2() {
		if (_addressLine2 == null) {
			return "";
		}
		else {
			return _addressLine2;
		}
	}

	@Override
	public void setAddressLine2(String addressLine2) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_addressLine2 = addressLine2;
	}

	@Override
	public String getCity() {
		if (_city == null) {
			return "";
		}
		else {
			return _city;
		}
	}

	@Override
	public void setCity(String city) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_city = city;
	}

	@Override
	public long getZipCode() {
		return _zipCode;
	}

	@Override
	public void setZipCode(long zipCode) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_zipCode = zipCode;
	}

	@Override
	public String getDesignation() {
		if (_designation == null) {
			return "";
		}
		else {
			return _designation;
		}
	}

	@Override
	public void setDesignation(String designation) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_designation = designation;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(EmployeeDetail.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), EmployeeDetail.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public EmployeeDetail toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, EmployeeDetail>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		EmployeeDetailImpl employeeDetailImpl = new EmployeeDetailImpl();

		employeeDetailImpl.setUuid(getUuid());
		employeeDetailImpl.setEmployeeId(getEmployeeId());
		employeeDetailImpl.setGroupId(getGroupId());
		employeeDetailImpl.setCompanyId(getCompanyId());
		employeeDetailImpl.setUserId(getUserId());
		employeeDetailImpl.setUserName(getUserName());
		employeeDetailImpl.setCreateDate(getCreateDate());
		employeeDetailImpl.setModifiedDate(getModifiedDate());
		employeeDetailImpl.setFirstName(getFirstName());
		employeeDetailImpl.setLastName(getLastName());
		employeeDetailImpl.setEmail(getEmail());
		employeeDetailImpl.setPhoneNumber(getPhoneNumber());
		employeeDetailImpl.setAddressLine1(getAddressLine1());
		employeeDetailImpl.setAddressLine2(getAddressLine2());
		employeeDetailImpl.setCity(getCity());
		employeeDetailImpl.setZipCode(getZipCode());
		employeeDetailImpl.setDesignation(getDesignation());

		employeeDetailImpl.resetOriginalValues();

		return employeeDetailImpl;
	}

	@Override
	public EmployeeDetail cloneWithOriginalValues() {
		EmployeeDetailImpl employeeDetailImpl = new EmployeeDetailImpl();

		employeeDetailImpl.setUuid(
			this.<String>getColumnOriginalValue("uuid_"));
		employeeDetailImpl.setEmployeeId(
			this.<Long>getColumnOriginalValue("employeeId"));
		employeeDetailImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		employeeDetailImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		employeeDetailImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		employeeDetailImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		employeeDetailImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		employeeDetailImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		employeeDetailImpl.setFirstName(
			this.<String>getColumnOriginalValue("firstName"));
		employeeDetailImpl.setLastName(
			this.<String>getColumnOriginalValue("lastName"));
		employeeDetailImpl.setEmail(
			this.<String>getColumnOriginalValue("email"));
		employeeDetailImpl.setPhoneNumber(
			this.<Long>getColumnOriginalValue("phoneNumber"));
		employeeDetailImpl.setAddressLine1(
			this.<String>getColumnOriginalValue("addressLine1"));
		employeeDetailImpl.setAddressLine2(
			this.<String>getColumnOriginalValue("addressLine2"));
		employeeDetailImpl.setCity(this.<String>getColumnOriginalValue("city"));
		employeeDetailImpl.setZipCode(
			this.<Long>getColumnOriginalValue("zipCode"));
		employeeDetailImpl.setDesignation(
			this.<String>getColumnOriginalValue("designation"));

		return employeeDetailImpl;
	}

	@Override
	public int compareTo(EmployeeDetail employeeDetail) {
		long primaryKey = employeeDetail.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof EmployeeDetail)) {
			return false;
		}

		EmployeeDetail employeeDetail = (EmployeeDetail)object;

		long primaryKey = employeeDetail.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<EmployeeDetail> toCacheModel() {
		EmployeeDetailCacheModel employeeDetailCacheModel =
			new EmployeeDetailCacheModel();

		employeeDetailCacheModel.uuid = getUuid();

		String uuid = employeeDetailCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			employeeDetailCacheModel.uuid = null;
		}

		employeeDetailCacheModel.employeeId = getEmployeeId();

		employeeDetailCacheModel.groupId = getGroupId();

		employeeDetailCacheModel.companyId = getCompanyId();

		employeeDetailCacheModel.userId = getUserId();

		employeeDetailCacheModel.userName = getUserName();

		String userName = employeeDetailCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			employeeDetailCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			employeeDetailCacheModel.createDate = createDate.getTime();
		}
		else {
			employeeDetailCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			employeeDetailCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			employeeDetailCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		employeeDetailCacheModel.firstName = getFirstName();

		String firstName = employeeDetailCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			employeeDetailCacheModel.firstName = null;
		}

		employeeDetailCacheModel.lastName = getLastName();

		String lastName = employeeDetailCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			employeeDetailCacheModel.lastName = null;
		}

		employeeDetailCacheModel.email = getEmail();

		String email = employeeDetailCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			employeeDetailCacheModel.email = null;
		}

		employeeDetailCacheModel.phoneNumber = getPhoneNumber();

		employeeDetailCacheModel.addressLine1 = getAddressLine1();

		String addressLine1 = employeeDetailCacheModel.addressLine1;

		if ((addressLine1 != null) && (addressLine1.length() == 0)) {
			employeeDetailCacheModel.addressLine1 = null;
		}

		employeeDetailCacheModel.addressLine2 = getAddressLine2();

		String addressLine2 = employeeDetailCacheModel.addressLine2;

		if ((addressLine2 != null) && (addressLine2.length() == 0)) {
			employeeDetailCacheModel.addressLine2 = null;
		}

		employeeDetailCacheModel.city = getCity();

		String city = employeeDetailCacheModel.city;

		if ((city != null) && (city.length() == 0)) {
			employeeDetailCacheModel.city = null;
		}

		employeeDetailCacheModel.zipCode = getZipCode();

		employeeDetailCacheModel.designation = getDesignation();

		String designation = employeeDetailCacheModel.designation;

		if ((designation != null) && (designation.length() == 0)) {
			employeeDetailCacheModel.designation = null;
		}

		return employeeDetailCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<EmployeeDetail, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<EmployeeDetail, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<EmployeeDetail, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((EmployeeDetail)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, EmployeeDetail>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					EmployeeDetail.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _employeeId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _firstName;
	private String _lastName;
	private String _email;
	private long _phoneNumber;
	private String _addressLine1;
	private String _addressLine2;
	private String _city;
	private long _zipCode;
	private String _designation;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<EmployeeDetail, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((EmployeeDetail)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("employeeId", _employeeId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("firstName", _firstName);
		_columnOriginalValues.put("lastName", _lastName);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("phoneNumber", _phoneNumber);
		_columnOriginalValues.put("addressLine1", _addressLine1);
		_columnOriginalValues.put("addressLine2", _addressLine2);
		_columnOriginalValues.put("city", _city);
		_columnOriginalValues.put("zipCode", _zipCode);
		_columnOriginalValues.put("designation", _designation);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("employeeId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("firstName", 256L);

		columnBitmasks.put("lastName", 512L);

		columnBitmasks.put("email", 1024L);

		columnBitmasks.put("phoneNumber", 2048L);

		columnBitmasks.put("addressLine1", 4096L);

		columnBitmasks.put("addressLine2", 8192L);

		columnBitmasks.put("city", 16384L);

		columnBitmasks.put("zipCode", 32768L);

		columnBitmasks.put("designation", 65536L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private EmployeeDetail _escapedModel;

}