/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.employee.service.model.impl;

import com.employee.service.model.EmployeeDetail;
import com.employee.service.service.EmployeeDetailLocalServiceUtil;

/**
 * The extended model base implementation for the EmployeeDetail service. Represents a row in the &quot;IgnekIntranet_EmployeeDetail&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link EmployeeDetailImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmployeeDetailImpl
 * @see EmployeeDetail
 * @generated
 */
public abstract class EmployeeDetailBaseImpl
	extends EmployeeDetailModelImpl implements EmployeeDetail {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a employee detail model instance should use the <code>EmployeeDetail</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			EmployeeDetailLocalServiceUtil.addEmployeeDetail(this);
		}
		else {
			EmployeeDetailLocalServiceUtil.updateEmployeeDetail(this);
		}
	}

}